name = "Molly"
description = "A blog theme based on Tufte CSS"
license = "MIT"
homepage = "https://github.com/timokratia/molly"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Zekun Hu"
homepage = "https://zekun.dev/"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
# [original]
# author =  "mdo"
# homepage = "http://markdotto.com/"
# repo = "https://www.github.com/mdo/hyde"